### ISSUE TITLE
Issue setting up

### ISSUE THREAD

**Issue by NotWasooked** [ErenKrt/Fivem-Server-Status#5]
Hi there,

Code works fine on the server code included but when i switch it we seem to run into this issue

![image](https://user-images.githubusercontent.com/62769780/108849224-d2cdfc80-75d9-11eb-926a-56ca5829a583.png)

Any ideas what is causing it. The code is correct.

**Comment by ErenKrt** [comment]
You need type server id right there. You can find server id from https://servers.fivem.net. 
Example;  Click the server then your url will be like that: https://servers.fivem.net/servers/detail/z98oby

After the "detail/" data is your server id.

If the problem persists, you can send what it wrote instead of the server id. If there is an error in the code I'll fix it.

**Comment by NotWasooked** [comment]
![image](https://user-images.githubusercontent.com/62769780/109048982-9c72a900-76cf-11eb-958d-7a907a2416c4.png)
 same issue.  could it be because we are using a form?

**Comment by NotWasooked** [comment]
This is the URL i used to get the code

https://servers.fivem.net/servers/detail/qqk7ez

**Comment by ErenKrt** [comment]
No, that was my mistake, i fixed code. If work with your server then u can close issue

**Comment by NotWasooked** [comment]
ill re download it and check.

**Comment by NotWasooked** [comment]
all working thank you for your support

![image](https://user-images.githubusercontent.com/62769780/109156577-e9ef2480-7768-11eb-9698-97c283e0c5aa.png)
